version: "3.8"
services:
  task-manager-app:
    container_name: task-manager-app
    build:
      dockerfile: Dockerfile
      context: ./
      target: build
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    command: npm run start
    environment:
      MONGO_USER: root
      MONGO_PASS: 1qwerty1
      MONGO_URL: mongo
      MONGO_PORT: 27017

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1qwerty1

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1qwerty1
      ME_CONFIG_MONGODB_URL: mongodb://root:1qwerty1@mongo:27017/